version: '3'
services:
  postgres:
    image: postgres:14
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data    
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'    

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/photo_twitter_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres